# Generated by Django 3.2.4 on 2023-09-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='subcategory_name',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
